services:
  htmly:
    build: .
    container_name: htmly
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - htmly_data:/var/www/html/content
    environment:
      - TZ=America/Sao_Paulo

volumes:
  htmly_data: