services:
  htmly:
    build: .
    container_name: htmly
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - htmly_data:/var/www/html/content
      - ./config.ini.example:/var/www/html/config/config.ini:ro
      - ./user.ini:/var/www/html/config/users/username.ini.example:ro
    environment:
      - TZ=America/Sao_Paulo

volumes:
  htmly_data: