name: htmly-build

on:
  push:
    branches:
      - master
      - 'test/**'
      - 'releases/**'
  workflow_dispatch:

jobs:
  docker_build_and_push:
    name: get docker image info
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.7'
          force: 'false'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Docker Image Details
        run: |
          app_name=$(jq -r '.name' package-lock.json)
          app_version=$(jq -r '.version' package-lock.json)

          echo "app_name: $app_name"
          echo "app_version: $app_version"
          echo "app_version=$app_version" >> $GITHUB_ENV
          echo "app_name=$app_name" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          load: true
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.app_name }}:${{ env.app_version }}

  tag_release:
    name: create tag and release
    needs: [docker_build_and_push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Docker Image Details
        run: |
          app_name=$(jq -r '.name' package-lock.json)
          app_version=$(jq -r '.version' package-lock.json)

          echo "app_name: $app_name"
          echo "app_version: $app_version"
          echo "app_version=$app_version" >> $GITHUB_ENV
          echo "app_name=$app_name" >> $GITHUB_ENV

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
        with:
          tag_name: v${{ env.app_version }}
          body: |
           HTMLy is an open source databaseless blogging platform prioritizes simplicity and speed written in PHP.
           It uses a unique algorithm to find or list any content based on date, type, category, tag, or author, and it's performance remain fast even if we have ten thousand of posts and hundreds of tags.

            What's New
            Autosave improvements
            Using grid layout for galleries
            See below for more details
            What's Changed
            Update get_pagination() - see #800 by @Joduai in #841
            Update zh_TW.ini by @XD9527 in #842
            Added Esperanto translation by @Voltinus in #850
            Cleaned up MFA by @KuJoe in #854
            Search improvements by @splifingate in #865